using System.IO;
StreamReader sr = new StreamReader(new BufferedStream(Console.OpenStandardInput()));
StreamWriter sw = new StreamWriter(new BufferedStream(Console.OpenStandardOutput()));
int a = int.Parse(sr.ReadLine());
            int b = int.Parse(sr.ReadLine());
            int c = int.Parse(sr.ReadLine());
            int d = int.Parse(sr.ReadLine());
            int e = int.Parse(sr.ReadLine());
            b = (b + d - 1) / d;
            c = (c + e - 1) / e;
            sw.Write(b > c ? a - b : a - c);
            sw.Flush();